### ISSUE TITLE
Dependency Issues on release

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Web_Kernel#11]
I noticed we have a dependency issue coming. I am not sure what will be the good way to resolve this.

Eg : Let us take  https://packagist.org/packages/aura/web-kernel

The Web_Kernel requires the below packages.

``` json
    php: >=5.4.0
    aura/project-kernel: 2.*@dev
    aura/dispatcher: 2.*@dev
    aura/router: 2.*@dev
    aura/web: 2.*@dev
    psr/log: 1.*
```

When we release a package, the dependencies may have been released with different versions. So even we release the beta, the dependencies are development.

Eg : see the 2.0.0-beta1 https://packagist.org/packages/aura/web-kernel 

May be in the composer.json we should have the latest stable release ? 

But it may not be true for all cases, may be we need to test with the development version of that branch.

What will be the best way to resolve these types of conflicts ?

Ping @simensen

**Comment by harikt** [comment]
My assumption is Beau will prefer to go with something like below 

``` json
{
    "require": {
        "php": ">=5.4.0",
        "aura/project-kernel": "2.0.0-beta1",
        "aura/dispatcher": "2.0.0-beta1",
        "aura/router": "2.0.0-beta1",
        "aura/web": "2.0.0-beta1",
        "psr/log": "1.*"
    },
    "autoload": {
        "psr-4": {
            "Aura\\Web_Kernel\\": "src/",
            "Aura\\Web_Kernel\\_Config\\": "config/"
        }
    },
    "extra": {
        "aura": {
            "type": "kernel",
            "config": {
                "common": "Aura\\Web_Kernel\\_Config\\Common",
                "kernel": "Aura\\Web_Kernel\\_Config\\Kernel"
            }
        },
        "branch-alias": {
            "dev-develop-2": "2.0.x-dev"
        }
    },
    "minimum-stability": "dev"
}
```

In this case I believe we don't need the `minimum-stability` flag also. It is the user who need to have it.

But one issue with this is after a beta release we may need to again change the composer.json file to make the dependencies list to `2.0.*@dev` . So if someone prefer to download `aura/web-kernel` beta will get the beta dependencies of the dependent package, and dev with dev version.

We may need to adjust our script to make something like this.

**Comment by harikt** [comment]
Further on this 

``` json
{
    "name": "aura/web-kernel",
    "type": "library",
    "description": "The kernel files for an Aura web project.",
    "keywords": [
        "web",
        "kernel"
    ],
    "homepage": "https://github.com/auraphp/Aura.Web_Kernel",
    "license": "BSD-2-Clause",
    "authors": [
        {
            "name": "Aura.Web_Kernel Contributors",
            "homepage": "https://github.com/auraphp/Aura.Web_Kernel/contributors"
        }
    ],
    "require": {
        "php": ">=5.4.0",
        "aura/project-kernel": "2.0.*",
        "aura/dispatcher": "2.0.*",
        "aura/router": "2.0.*",
        "aura/web": "2.0.*",
        "psr/log": "1.*"
    },
    "autoload": {
        "psr-4": {
            "Aura\\Web_Kernel\\": "src/",
            "Aura\\Web_Kernel\\_Config\\": "config/"
        }
    },
    "extra": {
        "aura": {
            "type": "kernel",
            "config": {
                "common": "Aura\\Web_Kernel\\_Config\\Common",
                "kernel": "Aura\\Web_Kernel\\_Config\\Kernel"
            }
        },
        "branch-alias": {
            "dev-develop-2": "2.0.x-dev"
        }
    },
    "minimum-stability": "dev"
}
```

I think we need to make it something like `"aura/router": "2.0.*",` so as the minumum-stability flag is there and once we are about to release we can remove the `"minimum-stability": "dev"` which will only install stable packages which helps to make in release.

Else we will end up with conflicts.
I would like to hear some thoughts on this. / ping @simensen our composer guru when you get some time.

Thanks!

**Comment by simensen** [comment]
I don't think there is anything wrong with requiring `2.*@dev`. It is far better than minimum-stability, I believe? It is sorta a tricky problem because you're doing two things when you require something:
- Define the versions of your package's dependancies that your package will work with
- Define the stability for each package installed _when installing_ **your package** _directly_

So in other words, you can say that your package works with 2.*, but when you are working on Aura.Web directly, you want to get @dev versions of those packages.

I believe that if you use something like `2.0.0-beta1` you are going to **force** your users to require @beta and you won't be able to install anything that uses Aura.Web without also explicitly either:
- Setting minimum-stability of their project to beta
- Manually requiring your same dependencies at beta
  - `"require": { "aura/project-kernel": "2.0.*@beta" }
  - `"require": { "aura/project-kernel": "@beta" }
  - `"require": { "aura/project-kernel": "2.0.0-beta1" }

None of these are very nice for your users.

Of course, at the point of @beta w/ no actual stable releases you will have to do something like this _anyway_, but y not requiring 2.0.0-beta1 you are doing some forward thinking and won't have to change things once you start releasing RC and stable releases.

**Comment by harikt** [comment]
@simensen my thoughts are for when we tag a release, beta, stable or what ever.

May be we need to change the `composer.json` before tagging a release.

**Comment by simensen** [comment]
> May be we need to change the `composer.json` before tagging a release.

I think this would become a maintenance issue pretty quickly. Unless you absolutely need to do this (unclear on the use case, to be honest) it would probably be better to set this up such that you do not need to remember to update `composer.json` before tagging.

Honestly, I think the most flexible option would be to require ~2.0@beta of your dependencies once you have beta dependencies available. Once you start having RC or stable dependencies available you can change it as needed.

I often use @dev in my library projects (I believe Aura.Web_Kernel would be a library project?) because I always want to work on dev of certain library dependencies.

Again, specifying stability in your library package is not _really_ meant to indicate that your package _only_ works with those versions. The stability is used for hinting against which stability dependencies you want when working on that package directly.

If you're working in a project that has no stable dependencies everything becomes more complicated. But you have to think about it as if you will eventually have stable dependencies.

**Comment by harikt** [comment]
Thank you @simensen .

> I believe Aura.Web_Kernel would be a library project?

It is basically the kernel for the framework. In composer term yes library.

**Comment by pmjones** [comment]
@harikt Now that the Kernels and Projects have been updated, do we believe this is still a problem?

**Comment by harikt** [comment]
@pmjones my concern was this when you have `"aura/router": "2.*@dev",` (https://github.com/auraphp/Aura.Web_Kernel/blob//6b56db302ce69716378427c32008f0efd4fac7c2/composer.json#L21) and  tagging v2 releases composer.json is pointing to dev branch. 

So Beau actually pointed out if you have a release then it is good to point like  `"aura/router": "~2.0.*",` or corresponding right version will help . ( Eg : `aura/html` will be `~2.1.*` for the service names will not work )

UPDATE : So we need to update the composer.json .
